# version format
version: 0.1.{build}-{branch}

skip_tags: false

skip_commits:
  message: /.*\[ci skip\]/       # Regex for matching commit message

# clone directory
clone_folder: c:\projects\ministaller

clone_depth: 3                      # clone entire repository history if not defined

before_build:
  - go version

build_script:
  - cmd: 'cd src'
  - go build -o ministaller.exe

after_build:
  - cmd: 'echo %cd%'
  - 7z a ministaller-latest.zip ministaller.exe
  - appveyor PushArtifact ministaller-latest.zip

before_test:
  - cmd: 'cd c:\projects\ministaller\src'
  - ps: wget 'https://github.com/Ribtoks/xpiks/releases/download/v1.1/Xpiks-qt-v1.1.3.zip' -OutFile "$pwd\xpiks-qt-v1.1.3.zip"
  - ps: 7z.exe x xpiks-qt-v1.1.3.zip -oC:\xpiks-qt-v1.1.3
  - ps: 7z.exe x xpiks-qt-v1.1.3.zip -oC:\xpiks-qt-v1.1.3-revert
  - ps: 7z.exe x xpiks-qt-v1.1.3.zip -oC:\xpiks-qt-v1.1.3-orig
  - ps: wget 'https://github.com/Ribtoks/xpiks/releases/download/v1.3.4/xpiks-qt-v1.3.4.zip' -OutFile "$pwd\xpiks-qt-v1.3.4.zip"
  - ps: 7z.exe x xpiks-qt-v1.3.4.zip -oC:\xpiks-qt-v1.3.4

test_script:
  - cmd: 'echo %cd%'
  - cmd: 'ministaller.exe -url "https://github.com/Ribtoks/xpiks/releases/download/v1.3.4/xpiks-qt-v1.3.4.zip" -stdout -install-path "c:/xpiks-qt-v1.1.3/xpiks-qt-v1.1.3" -package-path "xpiks-qt-v1.3.4.zip"'
  - diff -r c:\xpiks-qt-v1.1.3\xpiks-qt-v1.1.3 c:\xpiks-qt-v1.3.4\xpiks-qt-v1.3.4
  - cmd: 'ministaller.exe -stdout -install-path "c:/xpiks-qt-v1.1.3-revert/xpiks-qt-v1.1.3" -package-path "xpiks-qt-v1.3.4.zip" -fail'
  - diff -r c:\xpiks-qt-v1.1.3-revert\xpiks-qt-v1.1.3 c:\xpiks-qt-v1.1.3-orig\xpiks-qt-v1.1.3
