# version format
version: 0.1.{build}-{branch}

skip_tags: false

skip_commits:
  message: /.*\[ci skip\]/       # Regex for matching commit message

# clone directory
clone_folder: c:\projects\ministaller

environment:
  GOPATH: c:\gopath

clone_depth: 3                      # clone entire repository history if not defined

before_build:
  - go version

build_script:
  - make build

after_build:
  - cmd: 'echo %cd%'
  - 7z a ministaller-latest.zip ministaller.exe
  - appveyor PushArtifact ministaller-latest.zip

before_test:
  - cmd: 'cd c:\projects\ministaller'
  - ps: wget 'https://github.com/ribtoks/ministaller/archive/cde0bb0e8e79cda774a14a106d992167eb2fa4fe.zip' -OutFile "$pwd\test-archive.zip"
  - ps: 7z.exe x test-archive.zip -oC:\test-archive
  - ps: 7z.exe x test-archive.zip -oC:\test-archive-revert
  - ps: 7z.exe x test-archive.zip -oC:\test-archive-orig
  - ps: wget 'https://github.com/ribtoks/ministaller/archive/cde0bb0e8e79cda774a14a106d992167eb2fa4fe.zip' -OutFile "$pwd\ministaller-gold.zip"
  - ps: 7z.exe x ministaller-gold.zip -oC:\ministaller-gold

test_script:
  - cmd: 'echo %cd%'
  - cmd: 'ministaller.exe -url "https://github.com/ribtoks/ministaller/archive/cde0bb0e8e79cda774a14a106d992167eb2fa4fe.zip" -hash "1128ba06af51792b5f90ca0ba2884feb86b99dac" -stdout -install-path "c:/ministaller/test"'
  - diff -r c:\ministaller\test c:\ministaller-gold
  - cmd: 'ministaller.exe -stdout -install-path "c:/ministaller/test-revert" -package-path "xpiks-qt-v1.3.4.zip" -fail'
  - diff -r c:\ministaller\test-revert c:\ministaller-orig\xpiks-qt-v1.1.3
